# -*- coding: utf-8 -*-
"""utilities_data_2019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d6AjmtQ6CuAcjilBoVH4o88pWKzdwIjY

# Spending Analysis

Imoprt spending data from Github and load into Pandas dataframe.
"""

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

plt.style.use("ggplot")

url = 'https://raw.githubusercontent.com/technopharmer2000/py_dev/master/py_dev/matplotlib/spending_trends/utilities_data_2019.csv'
df = pd.read_csv(url)

"""Set x, y values and width variable."""

x_months = df['month']
x_indexes = np.arange(len(x_months))

y1_internet = df['Cox Internet '].astype(float)
y2_electric = df['Iluminating Co.'].astype(float)
y3_gas = df['Dominion Energy'].astype(float)
y4_water = df['Lakewood Water'].astype(float)
y5_total = df['total'].astype(float)
y6_split = df['3 way split'].astype(float)

width = 0.25

"""Instanciate figure for 2 graphs.

Plot 1 graph for variable utilities and 1 graph for total utilities cost.
"""

fig, (ax1, ax2) = plt.subplots(nrows=2, ncols=1, sharex=True)

ax1.bar(x_indexes - width, y4_water, width=width, label='Water')
ax1.bar(x_indexes, y2_electric, width=width, label='Electric')
ax1.bar(x_indexes + width, y3_gas, width=width, label='Gas')

ax1.legend()
ax1.set_title('Monthly House Costs')
ax1.set_ylabel('Cost')

ax2.bar(x_indexes, y5_total, label='Utilities Total')

ax2.legend()
ax2.set_ylabel('Cost')
ax2.set_xlabel('Month')

plt.xticks(ticks=x_indexes, labels=x_months, rotation=45)

plt.show()